[package]
name = "ring-io"
version = "0.0.3-pure-dev"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
crossbeam-utils = "0.8.1"
libc = "0.2.84"
